export const TOGGLE_WRAPPER = 'TOGGLE_WRAPPER';

export const ADD_QUESTION = 'ADD_QUESTION';
export const QUESTION_ADDED = 'QUESTION_ADDED';

export const CHANGE_QUESTION_TEXT = 'CHANGE_QUESTION_TEXT';
export const CHANGE_QUESTION_CATEGORY = 'CHANGE_QUESTION_CATEGORY';
export const ADD_QUESTION_IMAGE = 'ADD_QUESTION_IMAGE';
export const REMOVE_QUESTION_IMAGE = 'REMOVE_QUESTION_IMAGE';

export const ADD_ANSWER = 'ADD_ANSWER';
export const CHANGE_ANSWER_TEXT = 'CHANGE_ANSWER_TEXT';
export const REMOVE_ANSWER = 'REMOVE_ANSWER';

export const ADD_ANSWER_IMAGE = 'ADD_ANSWER_IMAGE';
export const REMOVE_ANSWER_IMAGE = 'REMOVE_ANSWER_IMAGE';







