export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const APPEND_QUESTIONS = 'APPEND_QUESTIONS';
export const CHOOSE_ANSWER = 'CHOOSE_ANSWER';
export const LIKE_QUESTION = 'LIKE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const FILTER_FEED = 'FILTER_FEED';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_FILTER_OFFSET = 'UPDATE_FILTER_OFFSET';




